export enum VALID_ENV_KEYS {
  OPENAI_API_KEY = "OPENAI_API_KEY",
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY",
  GOOGLE_GEMINI_API_KEY = "GOOGLE_GEMINI_API_KEY",
  MISTRAL_API_KEY = "MISTRAL_API_KEY",
  GROQ_API_KEY = "GROQ_API_KEY",
  PERPLEXITY_API_KEY = "PERPLEXITY_API_KEY",
  AZURE_OPENAI_SWEDEN_API_KEY = "AZURE_OPENAI_SWEDEN_API_KEY",
  AZURE_OPENAI_EUROPE_API_KEY = "AZURE_OPENAI_EUROPE_API_KEY",
  AZURE_OPENAI_SWISS_API_KEY = "AZURE_OPENAI_SWISS_API_KEY",

  OPENROUTER_API_KEY = "OPENROUTER_API_KEY",

  OPENAI_ORGANIZATION_ID = "OPENAI_ORGANIZATION_ID",

  AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT",
  AZURE_GPT_35_TURBO_NAME = "AZURE_GPT_35_TURBO_NAME",
  AZURE_GPT_45_VISION_NAME = "AZURE_GPT_45_VISION_NAME",
  AZURE_GPT_45_TURBO_NAME = "AZURE_GPT_45_TURBO_NAME",
  AZURE_GPT_4o_NAME = "AZURE_GPT_4o_NAME",
  AZURE_GPT_4o_MINI_NAME = "AZURE_GPT_4o_MINI_NAME",
  AZURE_o1_PREVIEW_NAME = "AZURE_o1_PREVIEW_NAME",
  AZURE_o1_NAME = "AZURE_o1_NAME",
  AZURE_o1_MINI_NAME = "AZURE_o1_MINI_NAME",
  AZURE_o3_MINI_NAME = "AZURE_o3_MINI_NAME",
  AZURE_EMBEDDINGS_NAME = "AZURE_EMBEDDINGS_NAME",
  AZURE_OPENAI_EUROPE_ENDPOINT = "AZURE_OPENAI_EUROPE_ENDPOINT",
  AZURE_GPT_4o_EUROPE_NAME = "AZURE_GPT_4o_EUROPE_NAME",
  AZURE_GPT_4o_MINI_EUROPE_NAME = "AZURE_GPT_4o_MINI_EUROPE_NAME",

  AZURE_OPENAI_SWISS_ENDPOINT = "AZURE_OPENAI_SWISS_ENDPOINT",
  AZURE_GPT_4O_MINI_SWISS_NAME = "AZURE_GPT_4O_MINI_SWISS_NAME"
}
